### PR TITLE
Enhance/169/add php73 support

### PR DESCRIPTION
**Pull request by otakumike**
implements #169

### CODE REVIEW

**Comment by garrettw** [comment]
Looks like all these PRs were created from the same branch and thus included more commits than you intended.

**Comment by otakumike** [comment]
> Looks like all these PRs were created from the same branch and thus included more commits than you intended.

We tend to chain our updates when we're on a roll. For example, we'll create branch A, then do more work on branch B as a clone from A. That way there's less chance of merge conflicts and we can test our latest features while also continuing to test our slightly older features. 

Works well when you're a team of two, wouldn't scale terribly well :)

**Comment by garrettw** [comment]
Oh ok, if it was intentional then carry on. I was just afraid it might have been a goof.

**Comment by otakumike** [comment]
Nope, but rest assured we'll make real goofs in other places :)

**Pull request merged**
