### PR TITLE
Feature/offline installer

### PR DESCRIPTION
**Pull request by yjimk**

### CODE REVIEW

**Comment by otakumike** [comment]
@yjimk Garrett has a point - should be "macos" now I think.

**Comment by yjimk** [comment]
No problem, shifted all references to `macos`. 

`darwin` on the other hand will probably have to stay as is unless golang changes its return value from `runtime.GOOS` and the conditional build for OS naming convention

**Comment by otakumike** [comment]
Agreed. I'm cool with 'darwin' and 'osx' internally.

**Comment by yjimk** [comment]
lol, `darwin` and `macos`

**Comment by garrettw** [comment]
"Darwin" is still current.

**Pull request merged**
