### PR TITLE
Feature/44/custom drupal filepaths

### LINKED ISSUE #44: Allow users to override the default Drupal files paths
The default public Files path and the Tokaido-specified Private files path aren't appropriate for every project:

```
$settings['file_private_path'] = '/tokaido/site/private/default/';
$settings['file_temporary_path'] = '/tmp';
```

For this feature, we should give users the ability to specify the three files paths (private, public, and temp) in their `.tok/config.yml` file. 

Tokaido should use this files in settings.tok.php, and also pre-create them and check permissions on them like it does for the default paths.

### PR DESCRIPTION
**Pull request by yjimk**
Resolves #44 

Well, mostly resolves IMO. 

> Tokaido should use this files in settings.tok.php, and also pre-create them and check permissions on them like it does for the default paths.

We weren't ever doing that with with `site/private/default` or `/tmp`, so wasn't sure if this is still a requirement. Might need a nudge in the right direction if you want to check these.

Merge and review after PR #62 and PR #63

### CODE REVIEW

**Comment by otakumike** [comment]
Will be good to get this out, but I think there's a couple of small things that we need to resolve first. 

1. I can't seem to set these values using config-set ? 
```
tok config-set drupal filepublicpath "/site/web/sites/default/files"
2018/10/30 07:50:27 `drupal filepublicpath` is not a valid Tokaido configuration path
```
Even though I can see them when I do a config-get:
```
tok config-get drupal
{
  Path: "web",
  Majorversion: "8",
  FilePublicPath: "",
  FilePrivatePath: "/site/private/default",
  FileTemporaryPath: "/tmp",
}
```

2. Just to make the config clear, the FilePublicPath should default to `site/{drupal_root}/sites/default/files`. This is the default for Drupal, but newer Drupal users might not understand that so I think it's best if we call out the config explicitly. 

3. I think we need to document how this works as well. Can you update the site repo?

**Comment by yjimk** [comment]
Couple of notes on your PR comments, sorry it's taken me so long to get around to it

1. Foiled by the capitalisation of struct props again, fixed
2. Added the default public path<site/{drupal_root}/sites/default/files>
3. https://github.com/ironstar-io/tokaido.io/pull/4

Also settings.tok.php wasn't being updated on config change, fixed that but raises a question about `hash_salt`. If that gets regenerated to a new value on each `tok up` is that going to cause an issue?

**Comment by otakumike** [comment]
Out of time to review this for 1.4.0, but will try to come back to it during the week

**Comment by yjimk** [comment]
This PR is well in the past now, closing

**Pull request closed without merging**
